### ISSUE TITLE
Using Discord SubCommands

### ISSUE THREAD

**Issue by fbrettnich** [AdriDevelopsThings/DiscordBirthdayBot#6]
The SlashCommands should be replaced by SubCommands, as follows:

`/set_birthday` => `/birthday set`
`/next_birthday` => `/birthday next`
`/forget_birthday` => `/birthday forget`

and so on..

This looks better and is easier to understand for users

More about this in the Discord Docs:
https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups

**Comment by AdriDevelopsThings** [comment]
/birthday = /birthday query
/birthday @User = /birthday query @User
/set_birthday <dd-mm> = /birthday set <dd-mm>
/birthday_calendar [mm] = /birthday calendar [mm]
/next_birthday = /birthday next
/today_birthday = /birthday today
/forget_birthday = /birthday forget
/enable_notifications = /notifications enable
/disable_notifications = /notifications disable

New command:
/settings help (same as /invite)
/set_notification_channel <#Channel> = /settings notification_channel set <#Channel>
/remove_notification_channel = /settings notifcation_channel remove
/set_language <lang> = /settings language (with selection menu)
/set_timezone <tz> = /settings timezone (with selection menu)
/fix_leaved_user_congratulations = /settings fix_leaved_user_congratulations
